### PR TITLE
Add an extra layer to support custom VRDevice

### PR DESCRIPTION
**Pull request by zazabe**
- force polyfill usage  
  we must always use the polyfill, even if the browser support WebVR API, because there's some missing part currently on native `VRDevice`, like the `k1`, `k2` lens properties.
- override native `*VRDevice` object, with support of the lens properties, etc...
- pass a collection of default `VRDevice` 
- use native `PositionSensorVRDevice` if available, or a simulated `PositionSensorVRDevice` (Mouse/Gyroscopic depending on the device) 
- use one of the default `HMDVRDevice`, selected based on the `HardwareUnitId` of the corresponding native `HMDVRDevice` if available, or the predefined default `HMDVRDevice`

### CODE REVIEW

**Comment by njam** [comment]
Should we still send this to upstream, referencing https://github.com/borismus/webvr-polyfill/issues/9 ?

**Comment by zazabe** [comment]
@njam our changes are too custom to do a PR on the main repo for now

**Comment by zazabe** [comment]
@njam 
If we want to trust only our device definition on CM, I suggest that we don't pass a collection of `HMDVRDevice` but just the one selected by the user (`CardboardHMDVRDevice` by default), without taking care of the WebVR API support for now.
For the `PositionSensorVRDevice`, we keep the same logic, we use the native if available, or the polyfill version (Gyro or Mouse).

**Comment by njam** [comment]
sgtm!

**Comment by zazabe** [comment]
@njam still gtm? ;)

**Comment by njam** [comment]
- cm/Polyfill.js: Can we use feature detection (on `deviceorientation`?) instead of using `isMobile()`?
- How about copying these files to the player, what we'll need to do anyway later?

**Comment by zazabe** [comment]
@njam for now, we can keep files here, this repo is used as a submodule in `rndmvr-player` so the built version is already available in the player, then we have to decide how we integrate the player into SK... it may change the strategy.

About the mobile detection, I agree, specially because `window.orientation` is the feature require by the Gyro sensor on mobile.

lgtm?

**Comment by vogdb** [comment]
Hi! I'm sorry but in case of native `navigator.getVRDevices` do we provision those native devices with additional info as distortion and etc? I just can't find the place where we do it.

**Comment by zazabe** [comment]
@vogdb we don't rely on the native WebVR API for the `HMDVRDevice`, we will always create a custom device based on the info coming from CM, but the native `PositionSensorVRDevice` will be used if available.

**Comment by vogdb** [comment]
oh, ok

**Comment by njam** [comment]
In that case `isMobile()` is probably the wrong name? Could we even inline it, or there are more usages?

**Comment by zazabe** [comment]
@njam ok, merge?

**Comment by njam** [comment]
lgtm

**Pull request merged**
