### PR TITLE
Update to the latest offical master version

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@njam seems they change the way the polyfill device sensor works, with something called "sensor fusion", I have to dig more to understand what is the diff but it seems interesting...

**Comment by njam** [comment]
Looks like it uses `devicemotion` events instead of `deviceorientation`.

> The device motion event is a superset of the device orientation event; it returns data about the rotation information and also acceleration information about the device. The acceleration data is returned in three axes: x, y and z.

http://www.html5rocks.com/en/tutorials/device/orientation/
Maybe this helps to improve the "motion prediction" to work better?

**Comment by zazabe** [comment]
@njam
yes, it seems to be the idea:

> FusedPositionSensorVRDevice uses DeviceMotionEvents and implements a complementary filter which does sensor fusion. This device also implements pose prediction, which greatly improves head tracking performance.
https://github.com/borismus/webvr-polyfill/blob/master/README.md

so the sensor polyfill used is defined like that:
1. native `PositionSensorVRDevice` if available
2. `FusionPositionSensorVRDevice`: if `DeviceMotionEvent` and `DeviceOrientationEvent` are supported
3. `OrientationPositionSensorVRDevice`: if only `DeviceOrientationEvent` is supported
4. `MouseKeyboardPositionSensorVRDevice`: if the Orientation API is not available

Note: 
- on Chrome 46, we can't test in emulated mobile mode    
the `window.orientation` property is not available, which is used by the orientation polyfill, so is this case, the `MouseKeyboardPositionSensorVRDevice` polyfill will be used and will not work because no mouse event are trigged in this mode.

**Comment by zazabe** [comment]
@njam  please review

**Comment by njam** [comment]
Hm difficult to review :)

Did you test it and it works on Chrome? If so then I'd say it's good!

**Comment by zazabe** [comment]
@njam It works on desktop with chrome 46, chromium WebVR and firefox 41, also on mobile with the fusion sensor, the only problem is with the mobile emulator, because `window.orientation` is not emulated (see my previous comment).

**Comment by njam** [comment]
Should it be `window.screen.orientation`? (https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation)
This is available in DevTools.

**Comment by zazabe** [comment]
@njam, i changed it to `window.screen.orientation` before and reverted my changes because this property is also available on desktop and in this case the `MouseKeyboardPositionSensorVRDevice` will never be used...

`window.orientation` seems not to be standard but the polyfill is heavily based on it... we can maybe try to find another way to detect if the browser support sensor, but it will not work with [Modernizr kind of tests](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/event/deviceorientation-motion.js#L28)...

**Comment by njam** [comment]
As discussed it's okay then. We can use actual devices for testing, and on desktop we use mouse.

**Comment by zazabe** [comment]
@njam merging here, but i'll migrate this source into SK directly, next time ill try to use `git subtree` to pull the latest source into SK

**Pull request merged**
